name: dineease
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  device_preview: ^1.2.0
  provider: ^6.1.2
  hive:
  hive_flutter:
  http:
  flutter_widget_from_html: ^0.15.1
  image_picker: ^1.1.2
  dotted_border: ^2.1.0
  carousel_slider: ^4.2.1
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  hive_generator:

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Poppins-SemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
    